import { z } from 'zod'
import { getThorNetworkType } from '@/services/thor'
import { veworldIndexerGetSingle } from '@/services/veworld-indexer'
import {
  IndexerGetStargateTotalVthoClaimedParamsSchema,
  IndexerStargateTotalVthoClaimedSchema,
} from '@/services/veworld-indexer/schemas'
import {
  createIndexerStructuredOutputSchema,
  createIndexerToolResponseSchema,
  indexerErrorResponse,
} from '@/services/veworld-indexer/utils'
import type { MCPTool } from '@/types'
import { logger } from '@/utils/logger'

export const IndexerStargateTotalVthoClaimedOutputSchema =
  createIndexerStructuredOutputSchema(IndexerStargateTotalVthoClaimedSchema)
export const IndexerStargateTotalVthoClaimedResponseSchema =
  createIndexerToolResponseSchema(IndexerStargateTotalVthoClaimedSchema)
export type IndexerStargateTotalVthoClaimedResponse = z.infer<
  typeof IndexerStargateTotalVthoClaimedResponseSchema
>

export const getStargateTotalVthoClaimed: MCPTool = {
  name: 'getStargateTotalVthoClaimed',
  title: 'Indexer: Stargate total VTHO claimed',
  description:
  'Fetch the total VTHO that Stargate users have actually claimed from rewards generated by delegations. Returns a numeric value encoded as a JSON string. Optional: blockNumber for historical snapshots; rewardsType can filter by LEGACY (pre‑Hayabusa) or DELEGATED (post‑Hayabusa).',
  inputSchema: IndexerGetStargateTotalVthoClaimedParamsSchema.shape,
  outputSchema: IndexerStargateTotalVthoClaimedOutputSchema.shape,
  annotations: {
    idempotentHint: true,
    openWorldHint: true,
    readOnlyHint: true,
    destructiveHint: false,
  },
  handler: async (params: z.infer<typeof IndexerGetStargateTotalVthoClaimedParamsSchema>) => {
    try {
      // Validate optional params
      IndexerGetStargateTotalVthoClaimedParamsSchema.parse(params)

      const data = await veworldIndexerGetSingle<string>({
        endPoint: '/api/v1/stargate/total-vtho-claimed',
        params,
      })
      if (data == null) {
        return indexerErrorResponse('Failed to fetch total VTHO claimed from VeWorld Indexer')
      }
      // API returns a plain JSON string, validate and pass through
      IndexerStargateTotalVthoClaimedSchema.parse(data)
      return {
        content: [{ type: 'text', text: data }],
        structuredContent: {
          ok: true,
          network: getThorNetworkType(),
          data,
        },
      }
    } catch (error) {
      logger.warn(`Error getting Stargate total VTHO claimed: ${String(error)}`)
      return indexerErrorResponse(`Error getting Stargate total VTHO claimed: ${String(error)}`)
    }
  },
}



