import { z } from 'zod'
import { getThorNetworkType } from '@/services/thor'
import { veworldIndexerGetSingle } from '@/services/veworld-indexer'
import {
  IndexerGetStargateTotalVthoGeneratedParamsSchema,
  IndexerStargateTotalVthoGeneratedSchema,
} from '@/services/veworld-indexer/schemas'
import {
  createIndexerStructuredOutputSchema,
  createIndexerToolResponseSchema,
  indexerErrorResponse,
} from '@/services/veworld-indexer/utils'
import type { MCPTool } from '@/types'
import { logger } from '@/utils/logger'

export const IndexerStargateTotalVthoGeneratedOutputSchema =
  createIndexerStructuredOutputSchema(IndexerStargateTotalVthoGeneratedSchema)
export const IndexerStargateTotalVthoGeneratedResponseSchema =
  createIndexerToolResponseSchema(IndexerStargateTotalVthoGeneratedSchema)
export type IndexerStargateTotalVthoGeneratedResponse = z.infer<
  typeof IndexerStargateTotalVthoGeneratedResponseSchema
>

export const getStargateTotalVthoGenerated: MCPTool = {
  name: 'getStargateTotalVthoGenerated',
  title: 'Indexer: Stargate total VTHO generated',
  description:
    'Fetch the total VTHO generated by Stargate delegations from validators’ block rewards (aggregate produced, whether or not claimed). Returns a numeric value encoded as a JSON string. Optional: blockNumber for historical snapshots.',
  inputSchema: IndexerGetStargateTotalVthoGeneratedParamsSchema.shape,
  outputSchema: IndexerStargateTotalVthoGeneratedOutputSchema.shape,
  annotations: {
    idempotentHint: true,
    openWorldHint: true,
    readOnlyHint: true,
    destructiveHint: false,
  },
  handler: async (params: z.infer<typeof IndexerGetStargateTotalVthoGeneratedParamsSchema>) => {
    try {
      IndexerGetStargateTotalVthoGeneratedParamsSchema.parse(params)

      const data = await veworldIndexerGetSingle<string>({
        endPoint: '/api/v1/stargate/total-vtho-generated',
        params,
      })
      if (data == null) {
        return indexerErrorResponse('Failed to fetch total VTHO generated from VeWorld Indexer')
      }
      IndexerStargateTotalVthoGeneratedSchema.parse(data)
      return {
        content: [{ type: 'text', text: data }],
        structuredContent: {
          ok: true,
          network: getThorNetworkType(),
          data,
        },
      }
    } catch (error) {
      logger.warn(`Error getting Stargate total VTHO generated: ${String(error)}`)
      return indexerErrorResponse(`Error getting Stargate total VTHO generated: ${String(error)}`)
    }
  },
}


