import { createMetricsByPeriodTool } from './get-stargate-metrics-by-period'

export const getStargateVthoGeneratedByPeriod = createMetricsByPeriodTool({
  name: 'getStargateVthoGeneratedByPeriod',
  title: 'Indexer: Stargate VTHO generated by period',
  pathPrefix: '/api/v1/stargate/vtho-generated',
  description:
    'Time‑series of VTHO generated from validators’ block rewards by period (DAY, WEEK, MONTH, YEAR, ALL). Each element represents the amount generated during that interval; use it to chart production over time.',
})


